# Starter pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

- task: CopyFiles@2
      inputs:
        SourceFolder: '$(Agent.BuildDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'ResourceDrop'
        publishLocation: 'Container'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


